version: "3.7"

services:
  waiter_server:
    build: ./repositories/waiter-api
    container_name: wellbe_waiter_server
    ports:
      - 3000:3000
    volumes:
      - ./repositories/waiter-api:/app
    depends_on:
      - mysql
      - waiter_sqs
    working_dir: /app
    command: npm start
    network_mode: 'host'

  waiter_communication:
    build: ./repositories/waiter-communication
    container_name: wellbe_waiter_communication
    volumes:
      - ./repositories/waiter-communication:/app
    ports:
      - 4001:4001
    depends_on:
      - waiter_sqs
    restart: on-failure
    working_dir: /app
    command: yarn start
    network_mode: 'host'

  mysql:
    image: mysql:5.6
    container_name: wellbe_waiter_mysql
    ports:
      - 33306:3306
    volumes:
      - /mysql/data:/var/lib/mysql
    restart: on-failure
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=wellbe_waiter
      - MYSQL_USER=root
    network_mode: 'host'

  waiter_sqs:
    image: roribio16/alpine-sqs
    container_name: wellbe_waiter_sqs
    ports:
      - 9324:9324
      - 9325:9325
    network_mode: 'host'
