version: "3.7"

services:
  mysql:
    image: mysql:5.6
    container_name: wellbe_waiter_mysql
    ports:
      - 33306:3306
    volumes:
      - /mysql/data:/var/lib/mysql
    restart: on-failure
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=wellbe_waiter
      - MYSQL_USER=root
    network_mode: 'host'

  waiter_server:
    build: ./repositories/waiter-api
    container_name: wellbe_waiter_server
    ports: 
      - 3000:3000
    volumes: 
      - ./repositories/waiter-api:/app
      - /app/node_modules
    depends_on:
      - mysql
    working_dir: /app
    command: npm start
    network_mode: 'host'

  waiter_frontend:
    build: 
      context: ./repositories/waiter-client
      target: develop-stage
    container_name: wellbe_waiter_client
    ports:
      - '8080:80'
    volumes:
      - './repositories/waiter-client:/app'
      - /app/node_modules
    command: /bin/sh -c "npm run serve"
    network_mode: 'host'